# Generated by Django 5.1.2 on 2025-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevCon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_by',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
