# Generated by Django 5.2.3 on 2025-06-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevCon', '0005_participents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participents',
            name='room_id',
        ),
        migrations.AddField(
            model_name='participents',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DevCon.room'),
            preserve_default=False,
        ),
    ]
